I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 504, in script
    hide 747
  File "game/script.rpy", line 504, in <module>
    hide 747
NameError: name 'with_777' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 504, in script
    hide 747
  File "/home/lastation4/Documents/renpy-7.3.5-sdk/renpy/ast.py", line 1832, in execute
    if renpy.python.py_eval(condition):
  File "/home/lastation4/Documents/renpy-7.3.5-sdk/renpy/python.py", line 2059, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/home/lastation4/Documents/renpy-7.3.5-sdk/renpy/python.py", line 2052, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 504, in <module>
    hide 747
NameError: name 'with_777' is not defined

Linux-5.4.0-58-generic-x86_64-with-debian-bullseye-sid
Ren'Py 7.3.5.606
Love Takes Flight prealpha0.3
Sun Dec 13 13:16:36 2020
